# Site settings
title: "Inside Mind"
description: "Ink & Ideals is a philosophical video essay series about pop culture and anime."
podcast-description: "Welcome to "Inside Mind" hosted by Loyd Osborne, the podcast where we fearlessly dive into mental health and those tough existential topics that are hard to navigate. Join Loyd as he has honest and raw conversations with experts and real people who have faced their inner demons, creating a safe space to be open and vulnerable. Get ready to explore the deep corners of the human mind, confront uncomfortable truths, and discover practical insights for self-discovery and growth. So, hop on board this transformative journey where we challenge norms, expand our understanding, and embrace the beautiful messiness of being human, one episode at a time."
url:  "https://insidemind.scyted.tv/" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Loyd Osborne"
  email: "loyd.osborne@scyted.tv"
  url: "https://scyted.tv/"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: loydosbornestv
  card: summary
facebook:
  app_id: 
logo: https://cdn.scyted.tv/assets/scytedtv/show/inside-mind/icons/icon.jpg
social:
  name: Alessio Franceschi
  links:
    - https://twitter.com/loydosbornestv
    - https://instagram.com/loydosbornestv
lang: it

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Inside Mind
podcast_author: Loyd Osborne
podcast_email: podcasts@scyted.tv
podcast_subtitle: "Welcome to "Inside Mind" hosted by Loyd Osborne, the podcast where we fearlessly dive into mental health and those tough existential topics that are hard to navigate."
podcast_summary: "Welcome to "Inside Mind" hosted by Loyd Osborne, the podcast where we fearlessly dive into mental health and those tough existential topics that are hard to navigate."
podcast_description: "Welcome to "Inside Mind" hosted by Loyd Osborne, the podcast where we fearlessly dive into mental health and those tough existential topics that are hard to navigate. Join Loyd as he has honest and raw conversations with experts and real people who have faced their inner demons, creating a safe space to be open and vulnerable. Get ready to explore the deep corners of the human mind, confront uncomfortable truths, and discover practical insights for self-discovery and growth. So, hop on board this transformative journey where we challenge norms, expand our understanding, and embrace the beautiful messiness of being human, one episode at a time."
podcast_explicit: "yes"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2023-06-01" #Launch date of your podcast
podcast_copyright: "&#xA9;ScytedTV Studios"
podcast_feed: 
podcast_artwork: "https://cdn.scyted.tv/assets/scytedtv/show/inside-mind/icons/icon.jpg"