name: Demo Notification job
on: [push]
jobs:
  First-Step:
    if: ${{ job.status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting GitHub Actions Job"
      - uses: cinotify/github-action@main
        with:
          to: 'status@scyted.tv'
          subject: 'UP'
          body: 'This is a notification from GitHub actions.'