name: Demo Notification job
on: [push]
jobs:
  First-Step:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting GitHub Actions Job"
      - uses: cinotify/github-action@main
        with:
          to: 'component+af6c0ecf-0174-4ba4-873c-3729a64ebf48@notifications.statuspage.io'
          subject: '${{ job.status }}'
          body: 'This is a notification from GitHub actions.'